### ISSUE TITLE
Newline doesn't work in tweet

### ISSUE THREAD

**Issue by orta** [ashfurrow/twelease#9]
<img width="581" alt="screen shot 2017-10-24 at 8 57 59 am" src="https://user-images.githubusercontent.com/49038/31944260-727f3d36-b899-11e7-9f4f-fe03ddaea9a0.png">

**Comment by ashfurrow** [comment]
Hmm, good catch. I'll take a look.

**Comment by SD10** [comment]
I don't know anything about `TypeScript` but I was looking into trying to solve this. 
Maybe we have to use `encodeURI()` on the `String` being used for the tweet? 😅

**Comment by orta** [comment]
That's an interesting idea ( though I don't _think_ that would fix it ) - I am also stumped TBH, I was wondering if there's a specific rule in the GitHub API client this lib uses about string interpolation

**Comment by ashfurrow** [comment]
So this is I think caused by using triple-brackets in the Moustache template, but we need that so that `http://` doesn't become `http&183;&whatever...;`. A hacky workaround could be to run the template, then replace newline escape sequences with actual newline characters. Does that seem like a reasonable solution, or is there a more general approach anyone would recommend?

**Comment by orta** [comment]
I'd make that change, I think `/n` is probably the only thing people would try to do that requires the unescaping

**Comment by ashfurrow** [comment]
Ahhhhh okay I think this is really a documentation/UI problem because the env var value text field on Heroku is _actually_ a multiline text box:

![screen shot 2017-11-05 at 7 55 10 pm](https://user-images.githubusercontent.com/498212/32421135-53201fe0-c263-11e7-98da-47b9ddbe997a.png)

When I used actual newlines in the variable worked: https://twitter.com/GreyEyesDev/status/927338457789280256

I'll update the readme with a note about newlines.
